services:
  tdbuilder:
    image: tdbuilder-app
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: tdbuilder
    ports:
      - "80:80"
    restart: unless-stopped
